import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { PurchaseState } from '../domain/purchase';
export const Paywall = ({ state, onPurchase, onRestore }: { state: PurchaseState; onPurchase:()=>void; onRestore:()=>void }) => {
 const busy = state === 'purchasing' || state === 'restoring' || state === 'purchased-awaiting-confirmation';
 const status = state === 'purchased-awaiting-confirmation' ? 'Payment received. Waiting for backend access confirmation…' : state === 'cancelled' ? 'Purchase cancelled. No charge was made.' : state === 'failed' ? 'Purchase failed. Your existing access is unchanged.' : state === 'restoring' ? 'Restoring purchases…' : '';
 return <View style={styles.card} accessibilityLabel="Subscription required"><Text style={styles.eyebrow}>SIMULATED BILLING</Text><Text style={styles.title}>Chat with Luna</Text><Text style={styles.copy}>Unlock creator chat and priority replies.</Text><Text style={styles.price}>$9.99 <Text style={styles.month}>/ month</Text></Text><Pressable accessibilityRole="button" disabled={busy} onPress={onPurchase} style={[styles.primary,busy&&styles.disabled]}><Text style={styles.primaryText}>{state==='purchasing'?'Purchasing…':state==='purchased-awaiting-confirmation'?'Confirming…':'Subscribe'}</Text></Pressable><Pressable accessibilityRole="button" disabled={busy} onPress={onRestore} style={styles.restore}><Text style={styles.restoreText}>Restore purchases</Text></Pressable>{!!status&&<Text accessibilityRole="alert" style={styles.status}>{status}</Text>}<Text style={styles.fine}>Demo only. No real payment is collected.</Text></View>;
};
const styles=StyleSheet.create({card:{margin:16,padding:22,borderRadius:24,backgroundColor:'#EBF6FE',borderWidth:1,borderColor:'#D3ECFD'},eyebrow:{fontSize:11,fontWeight:'800',letterSpacing:1,color:'#1B92E6'},title:{fontSize:25,fontWeight:'800',color:'#211C2B',marginTop:8},copy:{fontSize:15,color:'#655D6E',marginTop:5},price:{fontSize:26,fontWeight:'800',marginTop:18,color:'#211C2B'},month:{fontSize:14,fontWeight:'500'},primary:{marginTop:16,backgroundColor:'#53B5F7',borderRadius:14,padding:14,alignItems:'center'},disabled:{opacity:.5},primaryText:{color:'white',fontWeight:'800',fontSize:16},restore:{padding:13,alignItems:'center'},restoreText:{color:'#1B92E6',fontWeight:'700'},status:{textAlign:'center',color:'#35495E',fontSize:13,marginBottom:8},fine:{fontSize:11,textAlign:'center',color:'#687E92'}});
